springdoc:
  api-docs:
    enabled: ${APPLICATION_SWAGGER_ENABLED}
  swagger-ui:
    enabled: ${APPLICATION_SWAGGER_ENABLED}

app:
  security:
    swagger:
      public-enabled: ${APPLICATION_SWAGGER_ENABLED}
    csrf:
      cookie:
        path: /api/v1
        secure: true
        sameSite: Strict
