spring:
  main:
    web-application-type: none
  task:
    scheduling:
      enabled: false
  rabbitmq:
    dynamic: false
    listener:
      simple:
        auto-startup: false
      direct:
        auto-startup: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

app:
  owner:
    email: ${APPLICATION_OWNER_EMAIL}
  privilege:
    role:
      owner:
        key: owner
        name: Owner
      user:
        key: user
        name: User
