#!/bin/sh

echo "Auto-formatting code..."
./gradlew format

if [ $? -ne 0 ]; then
    echo ""
    echo "Auto-formatting failed!"
    exit 1
fi

echo "Running pre-commit checks..."
./gradlew lint

if [ $? -ne 0 ]; then
    echo ""
    echo "Pre-commit checks failed!"
    exit 1
fi

echo "All checks passed!"
exit 0
