logging:
  level:
    com.github.mohrezal.worker: DEBUG

spring:
  config:
    import: optional:file:../../.env[.properties]
  rabbitmq:
    host: ${APPLICATION_RABBIT_MQ_HOST}
    port: ${APPLICATION_RABBIT_MQ_PORT}
    username: ${APPLICATION_RABBIT_MQ_USERNAME}
    password: ${APPLICATION_RABBIT_MQ_PASSWORD}
  mail:
    host: ${APPLICATION_MAIL_HOST}
    port: ${APPLICATION_MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${APPLICATION_REDIS_HOST}
      port: ${APPLICATION_REDIS_PORT}
      password: ${APPLICATION_REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
app:
  mail:
    from: ${APPLICATION_MAIL_FROM}
  reminder:
    ttl: ${APPLICATION_VERIFICATION_REMINDER_TTL}
